/*
 * notify-config.h
 *
 * Copyright (C) 2022-2023 wolfSSL Inc.
 *
 * This file is part of wolfSentry.
 *
 * wolfSentry is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * wolfSentry is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

static const char* wolfsentry_config_data =
"{\n"
"    \"wolfsentry-config-version\" : 1,\n"
"    \"config-update\" : {\n"
"        \"max-connection-count\" : 0,\n"
"        \"penalty-box-duration\" : \"1h\",\n"
"        \"max-purgeable-routes\" : 10,\n"
"        \"derog-thresh-for-penalty-boxing\" : 4,\n"
"        \"derog-thresh-ignore-commendable\" : false,\n"
"        \"commendable-clears-derogatory\" : true\n"
"    },\n"
"    \"events-insert\" : [\n"
"        {\n"
"            \"label\" : \"event-on-insert\",\n"
"            \"actions\" : [ \"handle-insert\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"event-on-delete\",\n"
"            \"actions\" : [ \"handle-delete\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"event-on-match\",\n"
"            \"actions\" : [ \"handle-match\", \"notify-on-match\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"event-on-decision\",\n"
"            \"actions\" : [ \"notify-on-decision\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"transaction-successful\",\n"
"            \"actions\" : [ \"handle-transaction-successful\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"transaction-failed\",\n"
"            \"actions\" : [ \"handle-transaction-failed\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"handshake-failed\",\n"
"            \"actions\" : [ \"handle-handshake-failed\" ]\n"
"        },\n"
"        {\n"
"            \"label\" : \"dynamic-within-netblock\",\n"
"            \"config\" : {\n"
"                \"max-connection-count\" : 10,\n"
"                \"penalty-box-duration\" : \"1h\",\n"
"                \"derog-thresh-for-penalty-boxing\" : 4,\n"
"                \"derog-thresh-ignore-commendable\" : false,\n"
"                \"commendable-clears-derogatory\" : true,\n"
"                \"route-idle-time-for-purge\" : \"10m\"\n"
"            },\n"
"            \"decision-event\" : \"event-on-decision\"\n"
"        },\n"
"        {\n"
"            \"label\" : \"static-route-parent\",\n"
"            \"priority\" : 1,\n"
"            \"config\" : {\n"
"                \"max-connection-count\" : 10,\n"
"                \"penalty-box-duration\" : \"1h\",\n"
"                \"derog-thresh-for-penalty-boxing\" : 4\n"
"            },\n"
"            \"actions\" : [ \"handle-connect\", \"handle-connect2\" ],\n"
"            \"insert-event\" : \"event-on-insert\",\n"
"            \"match-event\" : \"event-on-match\",\n"
"            \"decision-event\" : \"event-on-decision\",\n"
"            \"delete-event\" : \"event-on-delete\"\n"
"        },\n"
"        {\n"
"            \"label\" : \"event-on-connect\",\n"
"            \"priority\" : 1,\n"
"            \"config\" : {\n"
"                \"max-connection-count\" : 10,\n"
"                \"penalty-box-duration\" : \"1h\",\n"
"                \"derog-thresh-for-penalty-boxing\" : 4\n"
"            },\n"
"            \"actions\" : [ \"handle-connect\", \"handle-connect2\" ],\n"
"            \"insert-event\" : \"event-on-insert\",\n"
"            \"match-event\" : \"event-on-match\",\n"
"            \"decision-event\" : \"event-on-decision\",\n"
"            \"delete-event\" : \"event-on-delete\"\n"
"        },\n"
"        {\n"
"            \"label\" : \"call-in-from-echo\"\n"
"        }\n"
"    ],\n"
"    \"default-policies\" : {\n"
"        \"default-policy\" : \"reject\",\n"
"        \"default-event\" : \"static-route-parent\"\n"
"    },\n"
"    \"static-routes-insert\" : [\n"
"        {\n"
"            \"parent-event\" : \"static-route-parent\",\n"
"            \"direction-in\" : true,\n"
"            \"direction-out\" : true,\n"
"            \"penalty-boxed\" : false,\n"
"            \"green-listed\" : true,\n"
"            \"dont-count-hits\" : false,\n"
"            \"dont-count-current-connections\" : true,\n"
"            \"family\" : 2,\n"
"            \"protocol\" : 6,\n"
"            \"remote\" : {\n"
"                \"address\" : \"127.0.0.1\",\n"
"                \"prefix-bits\" : 32\n"
"            }\n"
"        },\n"
"        {\n"
"            \"parent-event\" : \"static-route-parent\",\n"
"            \"direction-in\" : true,\n"
"            \"direction-out\" : true,\n"
"            \"penalty-boxed\" : false,\n"
"            \"green-listed\" : true,\n"
"            \"dont-count-hits\" : false,\n"
"            \"dont-count-current-connections\" : true,\n"
"            \"family\" : 2,\n"
"            \"protocol\" : 6,\n"
"            \"remote\" : {\n"
"                \"address\" : \"10.0.4.0\",\n"
"                \"prefix-bits\" : 16\n"
"            }\n"
"        },\n"
"        {\n"
"            \"parent-event\" : \"static-route-parent\",\n"
"            \"direction-in\" : true,\n"
"            \"direction-out\" : true,\n"
"            \"penalty-boxed\" : false,\n"
"            \"green-listed\" : true,\n"
"            \"dont-count-hits\" : false,\n"
"            \"dont-count-current-connections\" : true,\n"
"            \"family\" : 2,\n"
"            \"protocol\" : 6,\n"
"            \"remote\" : {\n"
"                \"address\" : \"192.168.0.0\",\n"
"                \"prefix-bits\" : 16,\n"
"                \"interface\" : 0\n"
"            }\n"
"        },\n"
"        {\n"
"            \"parent-event\" : \"static-route-parent\",\n"
"            \"direction-in\" : true,\n"
"            \"direction-out\" : true,\n"
"            \"penalty-boxed\" : false,\n"
"            \"green-listed\" : true,\n"
"            \"dont-count-hits\" : false,\n"
"            \"dont-count-current-connections\" : true,\n"
"            \"family\" : 2,\n"
"            \"protocol\" : 1,\n"
"            \"remote\" : {\n"
"                \"port\" : 8,\n"
"                \"address\" : \"192.168.0.0\",\n"
"                \"prefix-bits\" : 16,\n"
"                \"interface\" : 0\n"
"            }\n"
"        },\n"
"        {\n"
"            \"parent-event\" : \"static-route-parent\",\n"
"            \"direction-in\" : true,\n"
"            \"direction-out\" : true,\n"
"            \"penalty-boxed\" : false,\n"
"            \"green-listed\" : true,\n"
"            \"dont-count-hits\" : false,\n"
"            \"dont-count-current-connections\" : true,\n"
"            \"family\" : 118,\n"
"            \"remote\" : {\n"
"                \"address\" : \"de:c0:de:03:02:00\",\n"
"                \"prefix-bits\" : 40,\n"
"                \"interface\" : 0\n"
"            }\n"
"        }\n"
"    ],\n"
"    \"user-values\" : {\n"
"        \"notification-listen-addr\" : \"0.0.0.0\",\n"
"        \"notification-server-addr\" : \"127.0.0.1\",\n"
"        \"notification-dest-port\" : 55555,\n"
"        \"admin-listen-addr\" : \"0.0.0.0\",\n"
"        \"admin-listen-port\" : 10443,\n"
"        \"circlog-size\" : 100000\n"
"    }\n"
"}\n"
;
